# Generated by Django 5.2.4 on 2025-11-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answers',
            new_name='answers_count',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question'),
        ),
    ]
