# Generated by Django 5.2.4 on 2025-12-02 03:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_answercomments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerComments',
            new_name='AnswerComment',
        ),
    ]
