# Generated by Django 6.0.1 on 2026-02-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_questionbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_questions', to='questions.tag'),
        ),
    ]
