# Generated by Django 6.0.1 on 2026-02-12 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionroom',
            name='authorized_writers',
            field=models.ManyToManyField(blank=True, related_name='allowed_discussion_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionroom',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='banned_discussion_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WriteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_requests', to='chats.discussionroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
    ]
