# Generated by Django 5.2.4 on 2025-12-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('answer', 'Answer'), ('comment', 'Comment'), ('message', 'Message')], max_length=20),
        ),
    ]
