# Generated by Django 5.2.4 on 2025-12-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_noti_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('answer', 'Answer'), ('comment', 'Comment'), ('message', 'Message'), ('badge', 'Badge'), ('announcement', 'Announcement')], max_length=20),
        ),
    ]
